Repository CSC207-UofT/course-project-the-losers-club, pull requests merged in 2021-10, with the labels that each got.

#1 Add more detail to specification
  phase0/specification.md
Labels: documentation

#13 Revert unintended revert
  src/main/java/entities/Card.java
  src/main/java/entities/Deck.java
  src/main/java/entities/Hand.java
  src/main/java/usecases/CrazyEights.java
Labels: bug, enhancement

#14 Walkthrough and CRC update
  phase0/Walkthrough.txt
  phase0/crccards.pptx
  phase0/walkthrough.md
  src/main/java/entities/Card.java
Labels: documentation

#16 Add README
  README.md
Labels: documentation

#48 added UserManager and getters for User
  .gitignore
  src/main/java/entities/User.java
  src/main/java/usecases/UserManager.java
  src/test/java/usecases/UserManagerTest.java
Labels: enhancement
