Repository CSC207-UofT/course-project-the-losers-club, pull requests merged in 2021-11, with the labels that each got.

#52 Add game selection menu
  src/main/java/controllers/GameSelector.java
  src/main/java/drivers/Main.java
  src/main/java/presenters/console/Input.java
  src/main/java/presenters/console/Output.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/test/java/presenters/console/InputTest.java
  src/test/java/presenters/console/OutputTest.java
Labels: enhancement

#59 Add ability to seed a Deck shuffle
  src/main/java/entities/Deck.java
  src/main/java/usecases/CrazyEights.java
  src/test/java/entities/DeckTest.java
Labels: enhancement

#63 integrated user functionality
  src/main/java/controllers/GameSelector.java
  src/main/java/drivers/Main.java
  src/main/java/entities/User.java
  src/main/java/presenters/console/Input.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/Player.java
  src/main/java/usecases/UserManager.java
  src/test/java/entities/UserTest.java
  src/test/java/presenters/console/InputTest.java
  src/test/java/usecases/UserManagerTest.java
Labels: enhancement

#64 added username check
  src/main/java/presenters/console/Input.java
Labels: enhancement

#70 Added documentation to the CardCheck class and fixed regex.
  src/main/java/helpers/CardCheck.java
  src/test/java/helpers/CardCheckTest.java
Labels: documentation

#76 Hand sorting
  src/main/java/entities/CardComparors/SortByRankAceHigh.java
  src/main/java/entities/CardComparors/SortByRankAceLow.java
  src/main/java/entities/Hand.java
  src/main/java/usecases/Player.java
  src/test/java/entities/CardComparors/SortByRankAceHighTest.java
  src/test/java/entities/CardComparors/SortByRankAceLowTest.java
Labels: enhancement

#74 User manager serialization
  .gitignore
  src/main/java/controllers/GameSelector.java
  src/main/java/drivers/Main.java
  src/main/java/entities/User.java
  src/main/java/usecases/UserManager.java
  src/main/java/usecases/UserManagerExporter.java
  src/main/java/usecases/UserManagerImporter.java
  src/test/java/usecases/UserManagerExportImportTest.java
Labels: enhancement

#79 Fix game factory naming
  src/main/java/controllers/GameSelector.java
  src/main/java/usecases/GameTemplate.java
Labels: enhancement

#73 fixed an assortment of bugs found in GameSelector.java
  src/main/java/controllers/GameSelector.java
  src/main/java/entities/Hand.java
  src/main/java/entities/User.java
  src/main/java/presenters/console/Input.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/Player.java
  src/main/java/usecases/UserManager.java
  src/test/java/usecases/UserManagerTest.java
Labels: bug

#75 War
  src/main/java/drivers/Main.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/War.java
  src/test/java/usecases/WarTest.java
Labels: enhancement

#86 added user stat display
  src/main/java/controllers/GameSelector.java
  src/main/java/presenters/console/Input.java
  src/main/java/presenters/console/Output.java
  src/main/java/usecases/UserDisplay.java
Labels: enhancement

#87 Patch the user manager serialization process
  src/main/java/controllers/GameSelector.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/War.java
Labels: bug

#88 rounding error fix
  src/main/java/usecases/UserDisplay.java
Labels: bug

#89 added enforcement of min/max players to play the game
  src/main/java/controllers/GameSelector.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/War.java
Labels: enhancement

#82 Final version of GoFish
  src/main/java/drivers/Main.java
  src/main/java/entities/Hand.java
  src/main/java/entities/User.java
  src/main/java/presenters/console/Input.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/GoFish.java
  src/main/java/usecases/Player.java
  src/test/java/usecases/GoFishTest.java
  src/test/java/usecases/UserManagerTest.java
Labels: enhancement

#91 deck queue
  src/main/java/entities/Deck.java
Labels: enhancement

#92 Refactor `GameSelector` to be `MainMenu`
  src/main/java/controllers/MainMenu.java
  src/main/java/drivers/Main.java
  src/main/java/presenters/console/Input.java
  src/main/java/presenters/console/Output.java
  src/test/java/usecases/GoFishTest.java
Labels: enhancement

#94 Update README to reflect project state for phase 1
  README.md
Labels: enhancement

#95 Bug fixes and general code style improvements
  src/main/java/drivers/Main.java
  src/main/java/presenters/console/Input.java
  src/main/java/usecases/CrazyEights.java
  src/main/java/usecases/GameTemplate.java
  src/main/java/usecases/GoFish.java
  src/main/java/usecases/Player.java
  src/main/java/usecases/UserManager.java
  src/main/java/usecases/War.java
  src/test/java/usecases/GameTemplateTest.java
  src/test/java/usecases/GoFishTest.java
  src/test/java/usecases/WarTest.java
Labels: bug, documentation, enhancement

#97 Remove debug SOuts from CrazyEights
  src/main/java/usecases/CrazyEights.java
Labels: invalid

#96 Fix package naming typo
  src/main/java/entities/CardComparators/SortByRankAceHigh.java
  src/main/java/entities/CardComparators/SortByRankAceLow.java
  src/test/java/entities/CardComparators/SortByRankAceHighTest.java
  src/test/java/entities/CardComparators/SortByRankAceLowTest.java
Labels: invalid

#78 Phase1 written
  phase1/UMLs/ConsoleIO_Flow.png
  phase1/UMLs/CrazyEights_Dependencies.png
  phase1/UMLs/Game_Dependencies.png
  phase1/UMLs/User_Flow.png
  phase1/design_document.md
Labels: documentation

#107 Bura
  src/main/java/drivers/Main.java
  src/main/java/entities/Deck.java
  src/main/java/usecases/Bura.java
  src/main/java/usecases/GameTemplate.java
  src/test/java/usecases/BuraTest.java
Labels: enhancement
